services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.inner
    image: autoencoder
    deploy:
      replicas: 8
    network_mode: "host"

    volumes:
      - ./:/app
    
    environment:
      - PYTHONUNBUFFERED=1
